<?php 
$dataRIPS = [
    [
        "nombre" => "Consulta General",
        "codigo" => "001",
        "id" => 1,
        "precio" => 50,
    ],
    [
        "nombre" => "Revisión Dental",
        "codigo" => "002",
        "id" => 2,
        "precio" => 30,
    ],
    [
        "nombre" => "Análisis de Sangre",
        "codigo" => "003",
        "id" => 3,
        "precio" => 100,
    ],
    [
        "nombre" => "Ultrasonido",
        "codigo" => "004",
        "id" => 4,
        "precio" => 150,
    ],
    [
        "nombre" => "Radiografía",
        "codigo" => "005",
        "id" => 5,
        "precio" => 75,
    ],
    [
        "nombre" => "Consulta de Especialista",
        "codigo" => "006",
        "id" => 6,
        "precio" => 200,
    ],
    [
        "nombre" => "Terapia Física",
        "codigo" => "007",
        "id" => 7,
        "precio" => 120,
    ],
    [
        "nombre" => "Vacunación",
        "codigo" => "008",
        "id" => 8,
        "precio" => 25,
    ],
    [
        "nombre" => "Control de Peso",
        "codigo" => "009",
        "id" => 9,
        "precio" => 40,
    ],
    [
        "nombre" => "Consulta Dermatológica",
        "codigo" => "010",
        "id" => 10,
        "precio" => 90,
    ],
    [
        "nombre" => "Revisión Cardíaca",
        "codigo" => "011",
        "id" => 11,
        "precio" => 110,
    ],
    [
        "nombre" => "Examen de Vista",
        "codigo" => "012",
        "id" => 12,
        "precio" => 60,
    ],
    [
        "nombre" => "Chequeo General",
        "codigo" => "013",
        "id" => 13,
        "precio" => 150,
    ],
    [
        "nombre" => "Diagnóstico por Imágenes",
        "codigo" => "014",
        "id" => 14,
        "precio" => 80,
    ],
    [
        "nombre" => "Hormonas",
        "codigo" => "015",
        "id" => 15,
        "precio" => 200,
    ],
    [
        "nombre" => "Check-Up Anual",
        "codigo" => "016",
        "id" => 16,
        "precio" => 250,
    ],
    [
        "nombre" => "Test de Alergias",
        "codigo" => "017",
        "id" => 17,
        "precio" => 70,
    ],
    [
        "nombre" => "Electrocardiograma",
        "codigo" => "018",
        "id" => 18,
        "precio" => 130,
    ],
    [
        "nombre" => "Mamografía",
        "codigo" => "019",
        "id" => 19,
        "precio" => 220,
    ],
    [
        "nombre" => "Citogenética",
        "codigo" => "020",
        "id" => 20,
        "precio" => 190,
    ],
    [
        "nombre" => "Ortopedia",
        "codigo" => "021",
        "id" => 21,
        "precio" => 300,
    ],
    [
        "nombre" => "Neurología",
        "codigo" => "022",
        "id" => 22,
        "precio" => 150,
    ],
    [
        "nombre" => "Oncología",
        "codigo" => "023",
        "id" => 23,
        "precio" => 400,
    ],
    [
        "nombre" => "Psicología",
        "codigo" => "024",
        "id" => 24,
        "precio" => 90,
    ],
    [
        "nombre" => "Fisioterapia",
        "codigo" => "025",
        "id" => 25,
        "precio" => 100,
    ],
    [
        "nombre" => "Ginecología",
        "codigo" => "026",
        "id" => 26,
        "precio" => 130,
    ],
    [
        "nombre" => "Pediatría",
        "codigo" => "027",
        "id" => 27,
        "precio" => 80,
    ],
    [
        "nombre" => "Oftalmología",
        "codigo" => "028",
        "id" => 28,
        "precio" => 120,
    ],
    [
        "nombre" => "Cirugía General",
        "codigo" => "029",
        "id" => 29,
        "precio" => 500,
    ],
    [
        "nombre" => "Dermatología",
        "codigo" => "030",
        "id" => 30,
        "precio" => 140,
    ],
];


$dataEmpresas = [
    ["nombre" => "Empresa Uno S.A.S.", "nit" => "123456789-0"],
    ["nombre" => "Soluciones Tech S.A.", "nit" => "987654321-1"],
    ["nombre" => "Construcciones ABC Ltda.", "nit" => "234567890-2"],
    ["nombre" => "Alimentos y Bebidas S.A.", "nit" => "345678901-3"],
    ["nombre" => "Servicios Generales S.A.S.", "nit" => "456789012-4"],
    ["nombre" => "Transporte Rápido S.A.", "nit" => "567890123-5"],
    ["nombre" => "Consultoría Integral Ltda.", "nit" => "678901234-6"],
    ["nombre" => "Tecnología Avanzada S.A.S.", "nit" => "789012345-7"],
    ["nombre" => "Producciones Creativas S.A.", "nit" => "890123456-8"],
    ["nombre" => "Distribuciones Nacionales S.A.", "nit" => "901234567-9"],
];
