<?php 
//? ARCHIVO DE BARRIL, AQUI VAN TODOS LOS INCLUDES DE CONTROLLERS GENERALES
//? SOLO ES VALIDO PARA REALIZAR EL INCLUDE EN ARCHIVOS EN CARPETAS DE UN NIVEL DE LA RAIZ
//? EJ => RAIZ = MEDICAL/FE
//? VALIDO PARA MEDICAL/FE/NOMINA
//! NO SERA INCLUIDO EN ARCHIVOS DE SUBCARPETAS POSTERIORES MEDICAL/FE/NOMINA/OTRA/CARPETA

include __DIR__ . "/Moneda.php";
include __DIR__ . "/Paises.php";
// include __DIR__ . "/Email.php";
