<?php 
//? ARCHIVO DE BARRIL, AQUI VAN TODOS LOS INCLUDES DE MODELS GENERALES
//? SOLO ES VALIDO PARA REALIZAR EL INCLUDE EN ARCHIVOS EN CARPETAS DE UN NIVEL DE LA RAIZ
//? EJ => RAIZ = MEDICAL/FE
//? VALIDO PARA MEDICAL/FE/NOMINA
//! NO SERA INCLUIDO EN ARCHIVOS DE SUBCARPETAS POSTERIORES MEDICAL/FE/NOMINA/OTRA/CARPETA

require_once __DIR__ .  "/Monedas.php";
require_once __DIR__ .  "/Paises.php";

?>